### ISSUE TITLE
404 artifacts in README

### ISSUE THREAD

**Issue by rmartinsanta** [federicoPagnozzi/grammar2code#1]
The links in the README give 404 Not Found, probably should replace "files" with "distribution" in the links.

Example:
https://github.com/federicoPagnozzi/grammar2code/blob/master/files/grammar2code_osx.zip
![image](https://user-images.githubusercontent.com/55482385/184132758-ec95c16f-5228-4dfc-84d9-5eb105518079.png)

**Comment by federicoPagnozzi** [comment]
True, thanks for this message! 
I could not retrieve the compiled code so I had to remove the link to the compiled archive.
