### ISSUE TITLE
Crash due to high memory usage (possible memleak?)

### ISSUE THREAD

**Issue by rmartinsanta** [federicoPagnozzi/grammar2code#2]
While executing the grammar2code tool with the grammar available at https://github.com/federicoPagnozzi/emili/blob/master/grammars/grammar-pure.xml, the app crashes. Log:
```
❯ ./grammar2code grammars/grammar-pure.xml --depth=3 --parameters=tuning/parameters.txt
                                     ___            _
   __ _ _ _ __ _ _ __  _ __  __ _ _ |_  )__ ___  __| |___
  / _` | '_/ _` | '  \| '  \/ _` | '_/ // _/ _ \/ _` / -_)
  \__, |_| \__,_|_|_|_|_|_|_\__,_|_|/___\__\___/\__,_\___|
  |___/

Removing all occurrences of empty rule pfsp:nothing.
[1]    64876 killed     ./grammar2code grammars/grammar-pure.xml --depth=3
❯ ./grammar2code grammars/grammar-pure.xml --depth=3 --parameters=tuning/parameters.txt
                                     ___            _
   __ _ _ _ __ _ _ __  _ __  __ _ _ |_  )__ ___  __| |___
  / _` | '_/ _` | '  \| '  \/ _` | '_/ // _/ _ \/ _` / -_)
  \__, |_| \__,_|_|_|_|_|_|_\__,_|_|/___\__\___/\__,_\___|
  |___/

Removing all occurrences of empty rule pfsp:nothing.
[1]    64878 killed     ./grammar2code grammars/grammar-pure.xml --depth=3
```

Both times killed due to extremely high memory usage. Maybe is due to the grammar, or a wrong usage by me?

**Comment by federicoPagnozzi** [comment]
It can be that the program does not detect a circular dependency due to a bug, can you share the grammar file?
Also have you tried to decrease the depth?

**Comment by rmartinsanta** [comment]
The grammar file is grammar-pure.xml from the emili project, available [here](https://github.com/federicoPagnozzi/emili/blob/master/grammars/grammar-pure.xml). I have tested other grammar files and they seem to work fine. I will test different depths and report results. Thanks for the quick response!

**Comment by federicoPagnozzi** [comment]
Sorry for the very very late reply but I'm afraid that the problem is that in that grammar file there is some kind of loop that is not detected by grammar2code. I'll check but I would just be careful with dependency loops. 
Also that grammar refers to an early version of the emili framework that did not support online algorithm instantiation so it can be safely ignored.
